name: Upload FrameandCamera
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Run Build
        run: npm run build
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_API_KEY2: ${{ secrets.REACT_APP_API_KEY2 }}
          REACT_APP_API_KEY3: ${{ secrets.REACT_APP_API_KEY3 }}
          REACT_APP_API_KEY4: ${{ secrets.REACT_APP_API_KEY4 }}
          REACT_APP_API_KEY5: ${{ secrets.REACT_APP_API_KEY5 }}
          REACT_APP_API_KEY6: ${{ secrets.REACT_APP_API_KEY6 }}
          REACT_APP_API_KEY7: ${{ secrets.REACT_APP_API_KEY7 }}
          REACT_APP_API_KEY8: ${{ secrets.REACT_APP_API_KEY8 }}
          REACT_APP_API_KEY9: ${{ secrets.REACT_APP_API_KEY9 }}
          REACT_APP_API_KEY10: ${{ secrets.REACT_APP_API_KEY10 }}
      - name: Creating .env
        run: |
            echo "REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}" > .env.local
            echo "REACT_APP_API_KEY2=${{ secrets.REACT_APP_API_KEY2 }}" >> .env.local
            echo "REACT_APP_API_KEY3=${{ secrets.REACT_APP_API_KEY3 }}" >> .env.local
            echo "REACT_APP_API_KEY4=${{ secrets.REACT_APP_API_KEY4 }}" >> .env.local
            echo "REACT_APP_API_KEY5=${{ secrets.REACT_APP_API_KEY5 }}" >> .env.local
            echo "REACT_APP_API_KEY6=${{ secrets.REACT_APP_API_KEY6 }}" >> .env.local
            echo "REACT_APP_API_KEY7=${{ secrets.REACT_APP_API_KEY7 }}" >> .env.local
            echo "REACT_APP_API_KEY8=${{ secrets.REACT_APP_API_KEY8 }}" >> .env.local
            echo "REACT_APP_API_KEY9=${{ secrets.REACT_APP_API_KEY9 }}" >> .env.local
            echo "REACT_APP_API_KEY10=${{ secrets.REACT_APP_API_KEY10 }}" >> .env.local
      - name: Upload to AWS
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: "eu-west-1"
          SOURCE_DIR: "build"
